Repository freeCodeCamp-2025-Summer-Hackathon/maroon-socket, pull requests merged in 2025-07, with the labels that each got.

#9 Added issue template for tasks
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/task-form.yaml
Labels: misc

#26 feat: add health check on api/status
  server/app.js
Labels: server

#102 fix: return success as bool vals
  client/src/pages/Login.jsx
  client/src/services/authService.js
Labels: bug
